// flow-typed signature: d82bddf85b3f7ad9f39eaf12d938824a
// flow-typed version: <<STUB>>/apexcharts_v^3.39.0/flow_v0.205.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apexcharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apexcharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apexcharts/dist/apexcharts.amd' {
  declare module.exports: any;
}

declare module 'apexcharts/dist/apexcharts.common' {
  declare module.exports: any;
}

declare module 'apexcharts/dist/apexcharts.esm' {
  declare module.exports: any;
}

declare module 'apexcharts/dist/apexcharts' {
  declare module.exports: any;
}

declare module 'apexcharts/dist/apexcharts.min' {
  declare module.exports: any;
}

declare module 'apexcharts/src/apexcharts' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/Bar' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/BarStacked' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/BoxCandleStick' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/common/bar/DataLabels' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/common/bar/Helpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/common/circle/Helpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/common/line/Helpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/common/treemap/Helpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/HeatMap' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/Line' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/Pie' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/Radar' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/Radial' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/RangeBar' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/Scatter' {
  declare module.exports: any;
}

declare module 'apexcharts/src/charts/Treemap' {
  declare module.exports: any;
}

declare module 'apexcharts/src/libs/Treemap-squared' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Animations' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/annotations/Annotations' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/annotations/Helpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/annotations/PointsAnnotations' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/annotations/XAxisAnnotations' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/annotations/YAxisAnnotations' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/axes/Axes' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/axes/AxesUtils' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/axes/Grid' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/axes/XAxis' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/axes/YAxis' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Base' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Core' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/CoreUtils' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Crosshairs' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Data' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/DataLabels' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/dimensions/Dimensions' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/dimensions/Grid' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/dimensions/Helpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/dimensions/XAxis' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/dimensions/YAxis' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Events' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Exports' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Fill' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Filters' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Formatters' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Graphics' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/helpers/Destroy' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/helpers/InitCtxVariables' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/helpers/Localization' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/helpers/UpdateHelpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/legend/Helpers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/legend/Legend' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Markers' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Range' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Responsive' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Scales' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Series' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/settings/Config' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/settings/Defaults' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/settings/Globals' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/settings/Options' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Theme' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/TimeScale' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/TitleSubtitle' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/Toolbar' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/tooltip/AxesTooltip' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/tooltip/Intersect' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/tooltip/Labels' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/tooltip/Marker' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/tooltip/Position' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/tooltip/Utils' {
  declare module.exports: any;
}

declare module 'apexcharts/src/modules/ZoomPanSelection' {
  declare module.exports: any;
}

declare module 'apexcharts/src/svgjs/svg' {
  declare module.exports: any;
}

declare module 'apexcharts/src/utils/DateTime' {
  declare module.exports: any;
}

declare module 'apexcharts/src/utils/Resize' {
  declare module.exports: any;
}

declare module 'apexcharts/src/utils/Utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apexcharts/dist/apexcharts.amd.js' {
  declare module.exports: $Exports<'apexcharts/dist/apexcharts.amd'>;
}
declare module 'apexcharts/dist/apexcharts.common.js' {
  declare module.exports: $Exports<'apexcharts/dist/apexcharts.common'>;
}
declare module 'apexcharts/dist/apexcharts.esm.js' {
  declare module.exports: $Exports<'apexcharts/dist/apexcharts.esm'>;
}
declare module 'apexcharts/dist/apexcharts.js' {
  declare module.exports: $Exports<'apexcharts/dist/apexcharts'>;
}
declare module 'apexcharts/dist/apexcharts.min.js' {
  declare module.exports: $Exports<'apexcharts/dist/apexcharts.min'>;
}
declare module 'apexcharts/src/apexcharts.js' {
  declare module.exports: $Exports<'apexcharts/src/apexcharts'>;
}
declare module 'apexcharts/src/charts/Bar.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/Bar'>;
}
declare module 'apexcharts/src/charts/BarStacked.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/BarStacked'>;
}
declare module 'apexcharts/src/charts/BoxCandleStick.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/BoxCandleStick'>;
}
declare module 'apexcharts/src/charts/common/bar/DataLabels.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/common/bar/DataLabels'>;
}
declare module 'apexcharts/src/charts/common/bar/Helpers.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/common/bar/Helpers'>;
}
declare module 'apexcharts/src/charts/common/circle/Helpers.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/common/circle/Helpers'>;
}
declare module 'apexcharts/src/charts/common/line/Helpers.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/common/line/Helpers'>;
}
declare module 'apexcharts/src/charts/common/treemap/Helpers.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/common/treemap/Helpers'>;
}
declare module 'apexcharts/src/charts/HeatMap.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/HeatMap'>;
}
declare module 'apexcharts/src/charts/Line.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/Line'>;
}
declare module 'apexcharts/src/charts/Pie.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/Pie'>;
}
declare module 'apexcharts/src/charts/Radar.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/Radar'>;
}
declare module 'apexcharts/src/charts/Radial.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/Radial'>;
}
declare module 'apexcharts/src/charts/RangeBar.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/RangeBar'>;
}
declare module 'apexcharts/src/charts/Scatter.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/Scatter'>;
}
declare module 'apexcharts/src/charts/Treemap.js' {
  declare module.exports: $Exports<'apexcharts/src/charts/Treemap'>;
}
declare module 'apexcharts/src/libs/Treemap-squared.js' {
  declare module.exports: $Exports<'apexcharts/src/libs/Treemap-squared'>;
}
declare module 'apexcharts/src/modules/Animations.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Animations'>;
}
declare module 'apexcharts/src/modules/annotations/Annotations.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/annotations/Annotations'>;
}
declare module 'apexcharts/src/modules/annotations/Helpers.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/annotations/Helpers'>;
}
declare module 'apexcharts/src/modules/annotations/PointsAnnotations.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/annotations/PointsAnnotations'>;
}
declare module 'apexcharts/src/modules/annotations/XAxisAnnotations.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/annotations/XAxisAnnotations'>;
}
declare module 'apexcharts/src/modules/annotations/YAxisAnnotations.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/annotations/YAxisAnnotations'>;
}
declare module 'apexcharts/src/modules/axes/Axes.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/axes/Axes'>;
}
declare module 'apexcharts/src/modules/axes/AxesUtils.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/axes/AxesUtils'>;
}
declare module 'apexcharts/src/modules/axes/Grid.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/axes/Grid'>;
}
declare module 'apexcharts/src/modules/axes/XAxis.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/axes/XAxis'>;
}
declare module 'apexcharts/src/modules/axes/YAxis.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/axes/YAxis'>;
}
declare module 'apexcharts/src/modules/Base.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Base'>;
}
declare module 'apexcharts/src/modules/Core.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Core'>;
}
declare module 'apexcharts/src/modules/CoreUtils.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/CoreUtils'>;
}
declare module 'apexcharts/src/modules/Crosshairs.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Crosshairs'>;
}
declare module 'apexcharts/src/modules/Data.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Data'>;
}
declare module 'apexcharts/src/modules/DataLabels.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/DataLabels'>;
}
declare module 'apexcharts/src/modules/dimensions/Dimensions.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/dimensions/Dimensions'>;
}
declare module 'apexcharts/src/modules/dimensions/Grid.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/dimensions/Grid'>;
}
declare module 'apexcharts/src/modules/dimensions/Helpers.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/dimensions/Helpers'>;
}
declare module 'apexcharts/src/modules/dimensions/XAxis.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/dimensions/XAxis'>;
}
declare module 'apexcharts/src/modules/dimensions/YAxis.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/dimensions/YAxis'>;
}
declare module 'apexcharts/src/modules/Events.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Events'>;
}
declare module 'apexcharts/src/modules/Exports.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Exports'>;
}
declare module 'apexcharts/src/modules/Fill.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Fill'>;
}
declare module 'apexcharts/src/modules/Filters.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Filters'>;
}
declare module 'apexcharts/src/modules/Formatters.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Formatters'>;
}
declare module 'apexcharts/src/modules/Graphics.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Graphics'>;
}
declare module 'apexcharts/src/modules/helpers/Destroy.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/helpers/Destroy'>;
}
declare module 'apexcharts/src/modules/helpers/InitCtxVariables.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/helpers/InitCtxVariables'>;
}
declare module 'apexcharts/src/modules/helpers/Localization.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/helpers/Localization'>;
}
declare module 'apexcharts/src/modules/helpers/UpdateHelpers.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/helpers/UpdateHelpers'>;
}
declare module 'apexcharts/src/modules/legend/Helpers.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/legend/Helpers'>;
}
declare module 'apexcharts/src/modules/legend/Legend.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/legend/Legend'>;
}
declare module 'apexcharts/src/modules/Markers.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Markers'>;
}
declare module 'apexcharts/src/modules/Range.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Range'>;
}
declare module 'apexcharts/src/modules/Responsive.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Responsive'>;
}
declare module 'apexcharts/src/modules/Scales.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Scales'>;
}
declare module 'apexcharts/src/modules/Series.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Series'>;
}
declare module 'apexcharts/src/modules/settings/Config.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/settings/Config'>;
}
declare module 'apexcharts/src/modules/settings/Defaults.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/settings/Defaults'>;
}
declare module 'apexcharts/src/modules/settings/Globals.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/settings/Globals'>;
}
declare module 'apexcharts/src/modules/settings/Options.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/settings/Options'>;
}
declare module 'apexcharts/src/modules/Theme.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Theme'>;
}
declare module 'apexcharts/src/modules/TimeScale.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/TimeScale'>;
}
declare module 'apexcharts/src/modules/TitleSubtitle.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/TitleSubtitle'>;
}
declare module 'apexcharts/src/modules/Toolbar.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/Toolbar'>;
}
declare module 'apexcharts/src/modules/tooltip/AxesTooltip.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/tooltip/AxesTooltip'>;
}
declare module 'apexcharts/src/modules/tooltip/Intersect.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/tooltip/Intersect'>;
}
declare module 'apexcharts/src/modules/tooltip/Labels.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/tooltip/Labels'>;
}
declare module 'apexcharts/src/modules/tooltip/Marker.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/tooltip/Marker'>;
}
declare module 'apexcharts/src/modules/tooltip/Position.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/tooltip/Position'>;
}
declare module 'apexcharts/src/modules/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/tooltip/Tooltip'>;
}
declare module 'apexcharts/src/modules/tooltip/Utils.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/tooltip/Utils'>;
}
declare module 'apexcharts/src/modules/ZoomPanSelection.js' {
  declare module.exports: $Exports<'apexcharts/src/modules/ZoomPanSelection'>;
}
declare module 'apexcharts/src/svgjs/svg.js' {
  declare module.exports: $Exports<'apexcharts/src/svgjs/svg'>;
}
declare module 'apexcharts/src/utils/DateTime.js' {
  declare module.exports: $Exports<'apexcharts/src/utils/DateTime'>;
}
declare module 'apexcharts/src/utils/Resize.js' {
  declare module.exports: $Exports<'apexcharts/src/utils/Resize'>;
}
declare module 'apexcharts/src/utils/Utils.js' {
  declare module.exports: $Exports<'apexcharts/src/utils/Utils'>;
}
