// flow-typed signature: 71585a0a2dcc74af41f8b29f58786e72
// flow-typed version: <<STUB>>/babel-plugin-transform-require-context_v^0.1.1/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-require-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-require-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-transform-require-context/index' {
  declare module.exports: $Exports<'babel-plugin-transform-require-context'>;
}
declare module 'babel-plugin-transform-require-context/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-require-context'>;
}
