// flow-typed signature: d8aee6d07902d0a1a14152947c01ad2f
// flow-typed version: <<STUB>>/babel-preset-razzle_v^4.2.18/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-razzle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-razzle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-razzle/babel-plugins/commonjs' {
  declare module.exports: any;
}

declare module 'babel-preset-razzle/babel-plugins/jsx-pragma' {
  declare module.exports: any;
}

declare module 'babel-preset-razzle/babel-plugins/no-anonymous-default-export' {
  declare module.exports: any;
}

declare module 'babel-preset-razzle/babel-plugins/optimize-hook-destructuring' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-razzle/babel-plugins/commonjs.js' {
  declare module.exports: $Exports<'babel-preset-razzle/babel-plugins/commonjs'>;
}
declare module 'babel-preset-razzle/babel-plugins/jsx-pragma.js' {
  declare module.exports: $Exports<'babel-preset-razzle/babel-plugins/jsx-pragma'>;
}
declare module 'babel-preset-razzle/babel-plugins/no-anonymous-default-export.js' {
  declare module.exports: $Exports<'babel-preset-razzle/babel-plugins/no-anonymous-default-export'>;
}
declare module 'babel-preset-razzle/babel-plugins/optimize-hook-destructuring.js' {
  declare module.exports: $Exports<'babel-preset-razzle/babel-plugins/optimize-hook-destructuring'>;
}
declare module 'babel-preset-razzle/index' {
  declare module.exports: $Exports<'babel-preset-razzle'>;
}
declare module 'babel-preset-razzle/index.js' {
  declare module.exports: $Exports<'babel-preset-razzle'>;
}
