// flow-typed signature: ca1118971d7cc2765b82d4e11767ecf2
// flow-typed version: <<STUB>>/chalk_v5.3.0/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chalk/source' {
  declare module.exports: any;
}

declare module 'chalk/source/utilities' {
  declare module.exports: any;
}

declare module 'chalk/source/vendor/ansi-styles' {
  declare module.exports: any;
}

declare module 'chalk/source/vendor/supports-color/browser' {
  declare module.exports: any;
}

declare module 'chalk/source/vendor/supports-color' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chalk/source/index' {
  declare module.exports: $Exports<'chalk/source'>;
}
declare module 'chalk/source/index.js' {
  declare module.exports: $Exports<'chalk/source'>;
}
declare module 'chalk/source/utilities.js' {
  declare module.exports: $Exports<'chalk/source/utilities'>;
}
declare module 'chalk/source/vendor/ansi-styles/index' {
  declare module.exports: $Exports<'chalk/source/vendor/ansi-styles'>;
}
declare module 'chalk/source/vendor/ansi-styles/index.js' {
  declare module.exports: $Exports<'chalk/source/vendor/ansi-styles'>;
}
declare module 'chalk/source/vendor/supports-color/browser.js' {
  declare module.exports: $Exports<'chalk/source/vendor/supports-color/browser'>;
}
declare module 'chalk/source/vendor/supports-color/index' {
  declare module.exports: $Exports<'chalk/source/vendor/supports-color'>;
}
declare module 'chalk/source/vendor/supports-color/index.js' {
  declare module.exports: $Exports<'chalk/source/vendor/supports-color'>;
}
