// flow-typed signature: bc8ec999f601d82c1b15c2ac504c6e3c
// flow-typed version: <<STUB>>/eslint-plugin-security_v^3.0.1/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-security'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-security' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-security/eslint.config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-bidi-characters' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-buffer-noassert' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-child-process' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-disable-mustache-escape' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-eval-with-expression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-new-buffer' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-no-csrf-before-method-override' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-non-literal-fs-filename' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-non-literal-regexp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-non-literal-require' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-object-injection' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-possible-timing-attacks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-pseudoRandomBytes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-unsafe-regex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/configs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-bidi-characters' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-buffer-noassert' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-child-process' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-disable-mustache-escape' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-eval-with-expression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-new-buffer' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-no-csrf-before-method-override' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-non-literal-fs-filename' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-non-literal-regexp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-non-literal-require' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-object-injection' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-possible-timing-attacks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-pseudoRandomBytes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/rules/detect-unsafe-regexp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/utils/import-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/test/utils/is-static-expression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/utils/find-variable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/utils/import-utils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/utils/is-static-expression' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-security/eslint.config.js' {
  declare module.exports: $Exports<'eslint-plugin-security/eslint.config'>;
}
declare module 'eslint-plugin-security/index' {
  declare module.exports: $Exports<'eslint-plugin-security'>;
}
declare module 'eslint-plugin-security/index.js' {
  declare module.exports: $Exports<'eslint-plugin-security'>;
}
declare module 'eslint-plugin-security/rules/detect-bidi-characters.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-bidi-characters'>;
}
declare module 'eslint-plugin-security/rules/detect-buffer-noassert.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-buffer-noassert'>;
}
declare module 'eslint-plugin-security/rules/detect-child-process.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-child-process'>;
}
declare module 'eslint-plugin-security/rules/detect-disable-mustache-escape.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-disable-mustache-escape'>;
}
declare module 'eslint-plugin-security/rules/detect-eval-with-expression.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-eval-with-expression'>;
}
declare module 'eslint-plugin-security/rules/detect-new-buffer.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-new-buffer'>;
}
declare module 'eslint-plugin-security/rules/detect-no-csrf-before-method-override.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-no-csrf-before-method-override'>;
}
declare module 'eslint-plugin-security/rules/detect-non-literal-fs-filename.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-non-literal-fs-filename'>;
}
declare module 'eslint-plugin-security/rules/detect-non-literal-regexp.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-non-literal-regexp'>;
}
declare module 'eslint-plugin-security/rules/detect-non-literal-require.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-non-literal-require'>;
}
declare module 'eslint-plugin-security/rules/detect-object-injection.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-object-injection'>;
}
declare module 'eslint-plugin-security/rules/detect-possible-timing-attacks.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-possible-timing-attacks'>;
}
declare module 'eslint-plugin-security/rules/detect-pseudoRandomBytes.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-pseudoRandomBytes'>;
}
declare module 'eslint-plugin-security/rules/detect-unsafe-regex.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-unsafe-regex'>;
}
declare module 'eslint-plugin-security/test/configs/index' {
  declare module.exports: $Exports<'eslint-plugin-security/test/configs'>;
}
declare module 'eslint-plugin-security/test/configs/index.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/configs'>;
}
declare module 'eslint-plugin-security/test/rules/detect-bidi-characters.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-bidi-characters'>;
}
declare module 'eslint-plugin-security/test/rules/detect-buffer-noassert.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-buffer-noassert'>;
}
declare module 'eslint-plugin-security/test/rules/detect-child-process.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-child-process'>;
}
declare module 'eslint-plugin-security/test/rules/detect-disable-mustache-escape.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-disable-mustache-escape'>;
}
declare module 'eslint-plugin-security/test/rules/detect-eval-with-expression.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-eval-with-expression'>;
}
declare module 'eslint-plugin-security/test/rules/detect-new-buffer.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-new-buffer'>;
}
declare module 'eslint-plugin-security/test/rules/detect-no-csrf-before-method-override.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-no-csrf-before-method-override'>;
}
declare module 'eslint-plugin-security/test/rules/detect-non-literal-fs-filename.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-non-literal-fs-filename'>;
}
declare module 'eslint-plugin-security/test/rules/detect-non-literal-regexp.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-non-literal-regexp'>;
}
declare module 'eslint-plugin-security/test/rules/detect-non-literal-require.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-non-literal-require'>;
}
declare module 'eslint-plugin-security/test/rules/detect-object-injection.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-object-injection'>;
}
declare module 'eslint-plugin-security/test/rules/detect-possible-timing-attacks.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-possible-timing-attacks'>;
}
declare module 'eslint-plugin-security/test/rules/detect-pseudoRandomBytes.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-pseudoRandomBytes'>;
}
declare module 'eslint-plugin-security/test/rules/detect-unsafe-regexp.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/rules/detect-unsafe-regexp'>;
}
declare module 'eslint-plugin-security/test/utils/import-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/utils/import-utils'>;
}
declare module 'eslint-plugin-security/test/utils/is-static-expression.js' {
  declare module.exports: $Exports<'eslint-plugin-security/test/utils/is-static-expression'>;
}
declare module 'eslint-plugin-security/utils/find-variable.js' {
  declare module.exports: $Exports<'eslint-plugin-security/utils/find-variable'>;
}
declare module 'eslint-plugin-security/utils/import-utils.js' {
  declare module.exports: $Exports<'eslint-plugin-security/utils/import-utils'>;
}
declare module 'eslint-plugin-security/utils/is-static-expression.js' {
  declare module.exports: $Exports<'eslint-plugin-security/utils/is-static-expression'>;
}
