// flow-typed signature: da9de949ce5f96b48c4b9e17919eeeca
// flow-typed version: <<STUB>>/eslint-plugin-compat_v^6.0.2/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-compat/lib/cjs/src/config/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src/constants' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src/helpers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src/providers/caniuse-provider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src/providers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src/providers/mdn-provider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src/rules/compat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/cjs/src/types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/config/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/constants' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/helpers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/providers/caniuse-provider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/providers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/providers/mdn-provider' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/rules/compat' {
  declare module.exports: any;
}

declare module 'eslint-plugin-compat/lib/esm/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-compat/lib/cjs/src/config/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/config/recommended'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/constants.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/constants'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/helpers.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/helpers'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/index' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/providers/caniuse-provider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/providers/caniuse-provider'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/providers/index' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/providers'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/providers/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/providers'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/providers/mdn-provider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/providers/mdn-provider'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/rules/compat.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/rules/compat'>;
}
declare module 'eslint-plugin-compat/lib/cjs/src/types.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/cjs/src/types'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/config/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/config/recommended'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/constants.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/constants'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/helpers.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/helpers'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/index' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/providers/caniuse-provider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/providers/caniuse-provider'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/providers/index' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/providers'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/providers/index.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/providers'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/providers/mdn-provider.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/providers/mdn-provider'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/rules/compat.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/rules/compat'>;
}
declare module 'eslint-plugin-compat/lib/esm/src/types.js' {
  declare module.exports: $Exports<'eslint-plugin-compat/lib/esm/src/types'>;
}
