// flow-typed signature: 3a02ab340f5655bfaf6210ca68dc43d0
// flow-typed version: <<STUB>>/eslint-plugin-prettier_v^5.2.1/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-prettier/eslint-plugin-prettier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-prettier/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-prettier/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-prettier/eslint-plugin-prettier.js' {
  declare module.exports: $Exports<'eslint-plugin-prettier/eslint-plugin-prettier'>;
}
declare module 'eslint-plugin-prettier/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-prettier/recommended'>;
}
declare module 'eslint-plugin-prettier/worker.js' {
  declare module.exports: $Exports<'eslint-plugin-prettier/worker'>;
}
