// flow-typed signature: 66107353b9e722c5bd543fe59aadf49f
// flow-typed version: <<STUB>>/node-match-path_v0.6.3/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-match-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-match-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-match-path/lib/cjs' {
  declare module.exports: any;
}

declare module 'node-match-path/lib/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-match-path/lib/cjs.js' {
  declare module.exports: $Exports<'node-match-path/lib/cjs'>;
}
declare module 'node-match-path/lib/esm.js' {
  declare module.exports: $Exports<'node-match-path/lib/esm'>;
}
