// flow-typed signature: 08a62f62bbc70179e51858873d45a3c2
// flow-typed version: <<STUB>>/prettify-html_v^0.0.2/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettify-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettify-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'prettify-html/index' {
  declare module.exports: $Exports<'prettify-html'>;
}
declare module 'prettify-html/index.js' {
  declare module.exports: $Exports<'prettify-html'>;
}
