// flow-typed signature: b498a1a8288d4e1f620b5db2e0e52891
// flow-typed version: <<STUB>>/razzle-dev-utils_v^4.2.18/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'razzle-dev-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'razzle-dev-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'razzle-dev-utils/devServerMajor' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/FileSizeReporter' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/formatWebpackMessages' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/FriendlyErrorsPlugin' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/logger' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/makeLoaderFinder' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/prettyNodeErrors' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/printErrors' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/printWarnings' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/resolveRequest' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/setPorts' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/WebpackConfigHelpers' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/webpackHotDevClient' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/webpackHotDevClientV4' {
  declare module.exports: any;
}

declare module 'razzle-dev-utils/webpackMajor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'razzle-dev-utils/devServerMajor.js' {
  declare module.exports: $Exports<'razzle-dev-utils/devServerMajor'>;
}
declare module 'razzle-dev-utils/FileSizeReporter.js' {
  declare module.exports: $Exports<'razzle-dev-utils/FileSizeReporter'>;
}
declare module 'razzle-dev-utils/formatWebpackMessages.js' {
  declare module.exports: $Exports<'razzle-dev-utils/formatWebpackMessages'>;
}
declare module 'razzle-dev-utils/FriendlyErrorsPlugin.js' {
  declare module.exports: $Exports<'razzle-dev-utils/FriendlyErrorsPlugin'>;
}
declare module 'razzle-dev-utils/logger.js' {
  declare module.exports: $Exports<'razzle-dev-utils/logger'>;
}
declare module 'razzle-dev-utils/makeLoaderFinder.js' {
  declare module.exports: $Exports<'razzle-dev-utils/makeLoaderFinder'>;
}
declare module 'razzle-dev-utils/prettyNodeErrors.js' {
  declare module.exports: $Exports<'razzle-dev-utils/prettyNodeErrors'>;
}
declare module 'razzle-dev-utils/printErrors.js' {
  declare module.exports: $Exports<'razzle-dev-utils/printErrors'>;
}
declare module 'razzle-dev-utils/printWarnings.js' {
  declare module.exports: $Exports<'razzle-dev-utils/printWarnings'>;
}
declare module 'razzle-dev-utils/resolveRequest.js' {
  declare module.exports: $Exports<'razzle-dev-utils/resolveRequest'>;
}
declare module 'razzle-dev-utils/setPorts.js' {
  declare module.exports: $Exports<'razzle-dev-utils/setPorts'>;
}
declare module 'razzle-dev-utils/WebpackConfigHelpers.js' {
  declare module.exports: $Exports<'razzle-dev-utils/WebpackConfigHelpers'>;
}
declare module 'razzle-dev-utils/webpackHotDevClient.js' {
  declare module.exports: $Exports<'razzle-dev-utils/webpackHotDevClient'>;
}
declare module 'razzle-dev-utils/webpackHotDevClientV4.js' {
  declare module.exports: $Exports<'razzle-dev-utils/webpackHotDevClientV4'>;
}
declare module 'razzle-dev-utils/webpackMajor.js' {
  declare module.exports: $Exports<'razzle-dev-utils/webpackMajor'>;
}
