// flow-typed signature: b0a2c9a0fcd03f35d09319711f7b1823
// flow-typed version: <<STUB>>/razzle-plugin-scss_v^4.2.18/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'razzle-plugin-scss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'razzle-plugin-scss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'razzle-plugin-scss/helpers' {
  declare module.exports: any;
}

declare module 'razzle-plugin-scss/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'razzle-plugin-scss/helpers.js' {
  declare module.exports: $Exports<'razzle-plugin-scss/helpers'>;
}
declare module 'razzle-plugin-scss/index' {
  declare module.exports: $Exports<'razzle-plugin-scss'>;
}
declare module 'razzle-plugin-scss/index.js' {
  declare module.exports: $Exports<'razzle-plugin-scss'>;
}
declare module 'razzle-plugin-scss/tests/index.test.js' {
  declare module.exports: $Exports<'razzle-plugin-scss/tests/index.test'>;
}
