// flow-typed signature: 15428f7a7860f0423baa168cc3752e9e
// flow-typed version: <<STUB>>/razzle-plugin-svg-react-component_v^2.0.0/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'razzle-plugin-svg-react-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'razzle-plugin-svg-react-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'razzle-plugin-svg-react-component/index' {
  declare module.exports: $Exports<'razzle-plugin-svg-react-component'>;
}
declare module 'razzle-plugin-svg-react-component/index.js' {
  declare module.exports: $Exports<'razzle-plugin-svg-react-component'>;
}
