// flow-typed signature: d506f782503a0e58c8a9c8c27646741d
// flow-typed version: <<STUB>>/razzle-plugin-flow_v^1.0.0/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'razzle-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'razzle-plugin-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'razzle-plugin-flow/helpers' {
  declare module.exports: any;
}

declare module 'razzle-plugin-flow/tests/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'razzle-plugin-flow/helpers.js' {
  declare module.exports: $Exports<'razzle-plugin-flow/helpers'>;
}
declare module 'razzle-plugin-flow/index' {
  declare module.exports: $Exports<'razzle-plugin-flow'>;
}
declare module 'razzle-plugin-flow/index.js' {
  declare module.exports: $Exports<'razzle-plugin-flow'>;
}
declare module 'razzle-plugin-flow/tests/index.test.js' {
  declare module.exports: $Exports<'razzle-plugin-flow/tests/index.test'>;
}
