// flow-typed signature: e23ddba65ce7ccb5db99f25f8b88c785
// flow-typed version: <<STUB>>/react-helmet-async_v^2.0.5/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet-async/lib/index.esm' {
  declare module.exports: any;
}

declare module 'react-helmet-async/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-helmet-async/lib/index.esm.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/index.esm'>;
}
declare module 'react-helmet-async/lib/index' {
  declare module.exports: $Exports<'react-helmet-async/lib'>;
}
declare module 'react-helmet-async/lib/index.js' {
  declare module.exports: $Exports<'react-helmet-async/lib'>;
}
