// flow-typed signature: d03930b73af174105cd441572e82d1fb
// flow-typed version: <<STUB>>/react-ga4_v^2.1.0/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ga4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ga4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ga4/babel.config' {
  declare module.exports: any;
}

declare module 'react-ga4/dist/format' {
  declare module.exports: any;
}

declare module 'react-ga4/dist/ga4' {
  declare module.exports: any;
}

declare module 'react-ga4/dist/ga4.test' {
  declare module.exports: any;
}

declare module 'react-ga4/dist/gtag' {
  declare module.exports: any;
}

declare module 'react-ga4/dist' {
  declare module.exports: any;
}

declare module 'react-ga4/src/format' {
  declare module.exports: any;
}

declare module 'react-ga4/src/ga4' {
  declare module.exports: any;
}

declare module 'react-ga4/src/ga4.test' {
  declare module.exports: any;
}

declare module 'react-ga4/src/gtag' {
  declare module.exports: any;
}

declare module 'react-ga4/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ga4/babel.config.js' {
  declare module.exports: $Exports<'react-ga4/babel.config'>;
}
declare module 'react-ga4/dist/format.js' {
  declare module.exports: $Exports<'react-ga4/dist/format'>;
}
declare module 'react-ga4/dist/ga4.js' {
  declare module.exports: $Exports<'react-ga4/dist/ga4'>;
}
declare module 'react-ga4/dist/ga4.test.js' {
  declare module.exports: $Exports<'react-ga4/dist/ga4.test'>;
}
declare module 'react-ga4/dist/gtag.js' {
  declare module.exports: $Exports<'react-ga4/dist/gtag'>;
}
declare module 'react-ga4/dist/index' {
  declare module.exports: $Exports<'react-ga4/dist'>;
}
declare module 'react-ga4/dist/index.js' {
  declare module.exports: $Exports<'react-ga4/dist'>;
}
declare module 'react-ga4/src/format.js' {
  declare module.exports: $Exports<'react-ga4/src/format'>;
}
declare module 'react-ga4/src/ga4.js' {
  declare module.exports: $Exports<'react-ga4/src/ga4'>;
}
declare module 'react-ga4/src/ga4.test.js' {
  declare module.exports: $Exports<'react-ga4/src/ga4.test'>;
}
declare module 'react-ga4/src/gtag.js' {
  declare module.exports: $Exports<'react-ga4/src/gtag'>;
}
declare module 'react-ga4/src/index' {
  declare module.exports: $Exports<'react-ga4/src'>;
}
declare module 'react-ga4/src/index.js' {
  declare module.exports: $Exports<'react-ga4/src'>;
}
