// flow-typed signature: 1a406b23eee8312d235937a59c6166ef
// flow-typed version: <<STUB>>/react-responsive-modal_v^6.4.2/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-modal/dist' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/dist/react-responsive-modal.cjs.development' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/dist/react-responsive-modal.cjs.production.min' {
  declare module.exports: any;
}

declare module 'react-responsive-modal/dist/react-responsive-modal.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-modal/dist/index' {
  declare module.exports: $Exports<'react-responsive-modal/dist'>;
}
declare module 'react-responsive-modal/dist/index.js' {
  declare module.exports: $Exports<'react-responsive-modal/dist'>;
}
declare module 'react-responsive-modal/dist/react-responsive-modal.cjs.development.js' {
  declare module.exports: $Exports<'react-responsive-modal/dist/react-responsive-modal.cjs.development'>;
}
declare module 'react-responsive-modal/dist/react-responsive-modal.cjs.production.min.js' {
  declare module.exports: $Exports<'react-responsive-modal/dist/react-responsive-modal.cjs.production.min'>;
}
declare module 'react-responsive-modal/dist/react-responsive-modal.esm.js' {
  declare module.exports: $Exports<'react-responsive-modal/dist/react-responsive-modal.esm'>;
}
