// flow-typed signature: b88c0d36497535a7c723584f16b9bf1e
// flow-typed version: <<STUB>>/react-cool-onclickoutside_v^1.7.0/flow_v0.218.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cool-onclickoutside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cool-onclickoutside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cool-onclickoutside/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-cool-onclickoutside/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cool-onclickoutside/dist/index.esm.js' {
  declare module.exports: $Exports<'react-cool-onclickoutside/dist/index.esm'>;
}
declare module 'react-cool-onclickoutside/dist/index' {
  declare module.exports: $Exports<'react-cool-onclickoutside/dist'>;
}
declare module 'react-cool-onclickoutside/dist/index.js' {
  declare module.exports: $Exports<'react-cool-onclickoutside/dist'>;
}
