// flow-typed signature: 8123170e43b5b42d122bd56b13472ca4
// flow-typed version: <<STUB>>/react-apexcharts_v^1.4.0/flow_v0.205.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apexcharts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apexcharts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apexcharts/dist/react-apexcharts.iife.min' {
  declare module.exports: any;
}

declare module 'react-apexcharts/dist/react-apexcharts' {
  declare module.exports: any;
}

declare module 'react-apexcharts/dist/react-apexcharts.min' {
  declare module.exports: any;
}

declare module 'react-apexcharts/gulpfile' {
  declare module.exports: any;
}

declare module 'react-apexcharts/jest.config' {
  declare module.exports: any;
}

declare module 'react-apexcharts/rollup.config' {
  declare module.exports: any;
}

declare module 'react-apexcharts/src/react-apexcharts' {
  declare module.exports: any;
}

declare module 'react-apexcharts/src/react-apexcharts.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apexcharts/dist/react-apexcharts.iife.min.js' {
  declare module.exports: $Exports<'react-apexcharts/dist/react-apexcharts.iife.min'>;
}
declare module 'react-apexcharts/dist/react-apexcharts.js' {
  declare module.exports: $Exports<'react-apexcharts/dist/react-apexcharts'>;
}
declare module 'react-apexcharts/dist/react-apexcharts.min.js' {
  declare module.exports: $Exports<'react-apexcharts/dist/react-apexcharts.min'>;
}
declare module 'react-apexcharts/gulpfile.js' {
  declare module.exports: $Exports<'react-apexcharts/gulpfile'>;
}
declare module 'react-apexcharts/jest.config.js' {
  declare module.exports: $Exports<'react-apexcharts/jest.config'>;
}
declare module 'react-apexcharts/rollup.config.js' {
  declare module.exports: $Exports<'react-apexcharts/rollup.config'>;
}
declare module 'react-apexcharts/src/react-apexcharts.jsx' {
  declare module.exports: $Exports<'react-apexcharts/src/react-apexcharts'>;
}
declare module 'react-apexcharts/src/react-apexcharts.test.js' {
  declare module.exports: $Exports<'react-apexcharts/src/react-apexcharts.test'>;
}
