// flow-typed signature: c767acd24adbf0bb471d3a1aba85f484
// flow-typed version: <<STUB>>/react-dom_v^19.0.0/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dom/cjs/react-dom-client.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-client.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-profiling.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-profiling.profiling' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server-legacy.browser.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server-legacy.browser.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server-legacy.node.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server-legacy.node.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.browser.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.browser.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.bun.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.bun.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.edge.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.edge.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.node.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-server.node.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-test-utils.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom-test-utils.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom.production' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom.react-server.development' {
  declare module.exports: any;
}

declare module 'react-dom/cjs/react-dom.react-server.production' {
  declare module.exports: any;
}

declare module 'react-dom/client' {
  declare module.exports: any;
}

declare module 'react-dom/client.react-server' {
  declare module.exports: any;
}

declare module 'react-dom/profiling' {
  declare module.exports: any;
}

declare module 'react-dom/profiling.react-server' {
  declare module.exports: any;
}

declare module 'react-dom/react-dom.react-server' {
  declare module.exports: any;
}

declare module 'react-dom/server.browser' {
  declare module.exports: any;
}

declare module 'react-dom/server.bun' {
  declare module.exports: any;
}

declare module 'react-dom/server.edge' {
  declare module.exports: any;
}

declare module 'react-dom/server' {
  declare module.exports: any;
}

declare module 'react-dom/server.node' {
  declare module.exports: any;
}

declare module 'react-dom/server.react-server' {
  declare module.exports: any;
}

declare module 'react-dom/static.browser' {
  declare module.exports: any;
}

declare module 'react-dom/static.edge' {
  declare module.exports: any;
}

declare module 'react-dom/static' {
  declare module.exports: any;
}

declare module 'react-dom/static.node' {
  declare module.exports: any;
}

declare module 'react-dom/static.react-server' {
  declare module.exports: any;
}

declare module 'react-dom/test-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dom/cjs/react-dom-client.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-client.development'>;
}
declare module 'react-dom/cjs/react-dom-client.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-client.production'>;
}
declare module 'react-dom/cjs/react-dom-profiling.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-profiling.development'>;
}
declare module 'react-dom/cjs/react-dom-profiling.profiling.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-profiling.profiling'>;
}
declare module 'react-dom/cjs/react-dom-server-legacy.browser.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server-legacy.browser.development'>;
}
declare module 'react-dom/cjs/react-dom-server-legacy.browser.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server-legacy.browser.production'>;
}
declare module 'react-dom/cjs/react-dom-server-legacy.node.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server-legacy.node.development'>;
}
declare module 'react-dom/cjs/react-dom-server-legacy.node.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server-legacy.node.production'>;
}
declare module 'react-dom/cjs/react-dom-server.browser.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.browser.development'>;
}
declare module 'react-dom/cjs/react-dom-server.browser.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.browser.production'>;
}
declare module 'react-dom/cjs/react-dom-server.bun.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.bun.development'>;
}
declare module 'react-dom/cjs/react-dom-server.bun.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.bun.production'>;
}
declare module 'react-dom/cjs/react-dom-server.edge.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.edge.development'>;
}
declare module 'react-dom/cjs/react-dom-server.edge.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.edge.production'>;
}
declare module 'react-dom/cjs/react-dom-server.node.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.node.development'>;
}
declare module 'react-dom/cjs/react-dom-server.node.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-server.node.production'>;
}
declare module 'react-dom/cjs/react-dom-test-utils.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-test-utils.development'>;
}
declare module 'react-dom/cjs/react-dom-test-utils.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom-test-utils.production'>;
}
declare module 'react-dom/cjs/react-dom.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom.development'>;
}
declare module 'react-dom/cjs/react-dom.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom.production'>;
}
declare module 'react-dom/cjs/react-dom.react-server.development.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom.react-server.development'>;
}
declare module 'react-dom/cjs/react-dom.react-server.production.js' {
  declare module.exports: $Exports<'react-dom/cjs/react-dom.react-server.production'>;
}
declare module 'react-dom/client.js' {
  declare module.exports: $Exports<'react-dom/client'>;
}
declare module 'react-dom/client.react-server.js' {
  declare module.exports: $Exports<'react-dom/client.react-server'>;
}
declare module 'react-dom/index' {
  declare module.exports: $Exports<'react-dom'>;
}
declare module 'react-dom/index.js' {
  declare module.exports: $Exports<'react-dom'>;
}
declare module 'react-dom/profiling.js' {
  declare module.exports: $Exports<'react-dom/profiling'>;
}
declare module 'react-dom/profiling.react-server.js' {
  declare module.exports: $Exports<'react-dom/profiling.react-server'>;
}
declare module 'react-dom/react-dom.react-server.js' {
  declare module.exports: $Exports<'react-dom/react-dom.react-server'>;
}
declare module 'react-dom/server.browser.js' {
  declare module.exports: $Exports<'react-dom/server.browser'>;
}
declare module 'react-dom/server.bun.js' {
  declare module.exports: $Exports<'react-dom/server.bun'>;
}
declare module 'react-dom/server.edge.js' {
  declare module.exports: $Exports<'react-dom/server.edge'>;
}
declare module 'react-dom/server.js' {
  declare module.exports: $Exports<'react-dom/server'>;
}
declare module 'react-dom/server.node.js' {
  declare module.exports: $Exports<'react-dom/server.node'>;
}
declare module 'react-dom/server.react-server.js' {
  declare module.exports: $Exports<'react-dom/server.react-server'>;
}
declare module 'react-dom/static.browser.js' {
  declare module.exports: $Exports<'react-dom/static.browser'>;
}
declare module 'react-dom/static.edge.js' {
  declare module.exports: $Exports<'react-dom/static.edge'>;
}
declare module 'react-dom/static.js' {
  declare module.exports: $Exports<'react-dom/static'>;
}
declare module 'react-dom/static.node.js' {
  declare module.exports: $Exports<'react-dom/static.node'>;
}
declare module 'react-dom/static.react-server.js' {
  declare module.exports: $Exports<'react-dom/static.react-server'>;
}
declare module 'react-dom/test-utils.js' {
  declare module.exports: $Exports<'react-dom/test-utils'>;
}
