// flow-typed signature: 0a262606d5577bdc4470c0950c32296a
// flow-typed version: <<STUB>>/react-spinners_v0.15.0/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-spinners' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-spinners/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/cjs/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/assets/index-By4jh1P7' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/_getPrototype-B7BbOHMx' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/animation-CmKoZPRv' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/BarLoader.stories-CcASI_Fl' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/BeatLoader.stories-DxxBBdds' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/BounceLoader.stories-D0v2XF09' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/CircleLoader.stories-tdh7EeQa' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/ClimbingBoxLoader.stories-QMXRvDmk' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/ClipLoader.stories-Ci5Jrf2t' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/ClockLoader.stories-B2nzOA_0' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/Color-PRSJMWNM-CTtwmgtF' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/colors-DV-zfxfh' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/DocsRenderer-K4EAMTCU-CqygNVsi' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/DotLoader.stories-B3OBu3X7' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/entry-preview-Bdjjc83v' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/entry-preview-docs-Cnd6SSk3' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/FadeLoader.stories-DjFNWHZS' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/formatter-2WMMO6ZP-DXc4aD0z' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/GridLoader.stories-DI6IVIyr' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/HashLoader.stories-DR38duvM' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/iframe-5p6UzXUn' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/index-DrFu-skq' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/index-DXimoRZY' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/index-FeUjBnvO' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/index-uubelm5h' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/jsx-runtime-QvZ8i92b' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/MoonLoader.stories-B55gekmJ' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/PacmanLoader.stories-DsX-8Wr7' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-B4GcaC1c' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-BAz7FMXc' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-BmLvQvhz' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-BpcF_O6y' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-CJyji-Dt' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-Ct5NkTJf' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-CwqMn10d' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-Db4Idchh' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-Df8P57N3' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/preview-TCN6m6T-' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/PropagateLoader.stories-Bz7zRdxH' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/PuffLoader.stories-B763nhkv' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/PulseLoader.stories-Q849BcQr' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/react-18-dxeXy74A' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/RingLoader.stories-BK7q4TmV' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/RiseLoader.stories-BkdUmN5k' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/RotateLoader.stories-BL0wUnff' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/ScaleLoader.stories-E4q-HnXP' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/SkewLoader.stories-D7Yys5ID' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/SquareLoader.stories-BB_nH-b2' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/SyncLoader.stories-3_2T-rjZ' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/syntaxhighlighter-BP7B2CQK-D5V8MPXO' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/assets/WithTooltip-KJL26V4Q-BoukyuhG' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/essentials-actions-3/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/essentials-backgrounds-4/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/essentials-controls-2/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/essentials-measure-7/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/essentials-outline-8/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/essentials-toolbars-6/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/essentials-viewport-5/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/interactions-9/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/links-1/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/storybook-13/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/storybook-canonical-link-12/register-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/storybook-core-server-presets-0/common-manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/storybook-dark-mode-esm-preset-10/manager-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-addons/storybook-google-analytics-v4-11/register-bundle' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/chunk-B3YDJJJH' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/chunk-BLWCBWKL' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/chunk-GUVK2GTO' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/chunk-LFRML3ZV' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/chunk-MC7RAF2B' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/chunk-ZR5JZWHI' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/formatter-2WMMO6ZP-JI7RHVTW' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/globals-module-info' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/globals-runtime' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/globals' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/runtime' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/syntaxhighlighter-BP7B2CQK-WOJYHKQR' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-manager/WithTooltip-KJL26V4Q-5LS5AN27' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-preview/globals' {
  declare module.exports: any;
}

declare module 'react-spinners/dist/storybook/sb-preview/runtime' {
  declare module.exports: any;
}

declare module 'react-spinners/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/esm' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/esm/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/SyncLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/BarLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/BeatLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/BounceLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/CircleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ClimbingBoxLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ClipLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ClockLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/DotLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/FadeLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/GridLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/HashLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/animation' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/animation.server.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/animation.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/colors' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/colors.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/props' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/unitConverter' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/helpers/unitConverter.test' {
  declare module.exports: any;
}

declare module 'react-spinners/umd' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/MoonLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PacmanLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PropagateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PuffLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/PulseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/RingLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/RiseLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/RotateLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/ScaleLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/SkewLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/SquareLoader' {
  declare module.exports: any;
}

declare module 'react-spinners/umd/SyncLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-spinners/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/BarLoader'>;
}
declare module 'react-spinners/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/BeatLoader'>;
}
declare module 'react-spinners/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/BounceLoader'>;
}
declare module 'react-spinners/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/CircleLoader'>;
}
declare module 'react-spinners/cjs/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/BarLoader'>;
}
declare module 'react-spinners/cjs/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/BeatLoader'>;
}
declare module 'react-spinners/cjs/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/BounceLoader'>;
}
declare module 'react-spinners/cjs/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/CircleLoader'>;
}
declare module 'react-spinners/cjs/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ClimbingBoxLoader'>;
}
declare module 'react-spinners/cjs/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ClipLoader'>;
}
declare module 'react-spinners/cjs/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ClockLoader'>;
}
declare module 'react-spinners/cjs/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/DotLoader'>;
}
declare module 'react-spinners/cjs/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/FadeLoader'>;
}
declare module 'react-spinners/cjs/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/GridLoader'>;
}
declare module 'react-spinners/cjs/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/HashLoader'>;
}
declare module 'react-spinners/cjs/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/animation'>;
}
declare module 'react-spinners/cjs/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/animation.server.test'>;
}
declare module 'react-spinners/cjs/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/animation.test'>;
}
declare module 'react-spinners/cjs/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/colors'>;
}
declare module 'react-spinners/cjs/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/colors.test'>;
}
declare module 'react-spinners/cjs/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/props'>;
}
declare module 'react-spinners/cjs/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/unitConverter'>;
}
declare module 'react-spinners/cjs/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/cjs/helpers/unitConverter.test'>;
}
declare module 'react-spinners/cjs/index' {
  declare module.exports: $Exports<'react-spinners/cjs'>;
}
declare module 'react-spinners/cjs/index.js' {
  declare module.exports: $Exports<'react-spinners/cjs'>;
}
declare module 'react-spinners/cjs/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/MoonLoader'>;
}
declare module 'react-spinners/cjs/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PacmanLoader'>;
}
declare module 'react-spinners/cjs/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PropagateLoader'>;
}
declare module 'react-spinners/cjs/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PuffLoader'>;
}
declare module 'react-spinners/cjs/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/PulseLoader'>;
}
declare module 'react-spinners/cjs/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/RingLoader'>;
}
declare module 'react-spinners/cjs/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/RiseLoader'>;
}
declare module 'react-spinners/cjs/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/RotateLoader'>;
}
declare module 'react-spinners/cjs/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/ScaleLoader'>;
}
declare module 'react-spinners/cjs/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/SkewLoader'>;
}
declare module 'react-spinners/cjs/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/SquareLoader'>;
}
declare module 'react-spinners/cjs/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/cjs/SyncLoader'>;
}
declare module 'react-spinners/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClimbingBoxLoader'>;
}
declare module 'react-spinners/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClipLoader'>;
}
declare module 'react-spinners/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/ClockLoader'>;
}
declare module 'react-spinners/dist/assets/index-By4jh1P7.js' {
  declare module.exports: $Exports<'react-spinners/dist/assets/index-By4jh1P7'>;
}
declare module 'react-spinners/dist/storybook/assets/_getPrototype-B7BbOHMx.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/_getPrototype-B7BbOHMx'>;
}
declare module 'react-spinners/dist/storybook/assets/animation-CmKoZPRv.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/animation-CmKoZPRv'>;
}
declare module 'react-spinners/dist/storybook/assets/BarLoader.stories-CcASI_Fl.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/BarLoader.stories-CcASI_Fl'>;
}
declare module 'react-spinners/dist/storybook/assets/BeatLoader.stories-DxxBBdds.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/BeatLoader.stories-DxxBBdds'>;
}
declare module 'react-spinners/dist/storybook/assets/BounceLoader.stories-D0v2XF09.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/BounceLoader.stories-D0v2XF09'>;
}
declare module 'react-spinners/dist/storybook/assets/CircleLoader.stories-tdh7EeQa.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/CircleLoader.stories-tdh7EeQa'>;
}
declare module 'react-spinners/dist/storybook/assets/ClimbingBoxLoader.stories-QMXRvDmk.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/ClimbingBoxLoader.stories-QMXRvDmk'>;
}
declare module 'react-spinners/dist/storybook/assets/ClipLoader.stories-Ci5Jrf2t.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/ClipLoader.stories-Ci5Jrf2t'>;
}
declare module 'react-spinners/dist/storybook/assets/ClockLoader.stories-B2nzOA_0.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/ClockLoader.stories-B2nzOA_0'>;
}
declare module 'react-spinners/dist/storybook/assets/Color-PRSJMWNM-CTtwmgtF.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/Color-PRSJMWNM-CTtwmgtF'>;
}
declare module 'react-spinners/dist/storybook/assets/colors-DV-zfxfh.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/colors-DV-zfxfh'>;
}
declare module 'react-spinners/dist/storybook/assets/DocsRenderer-K4EAMTCU-CqygNVsi.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/DocsRenderer-K4EAMTCU-CqygNVsi'>;
}
declare module 'react-spinners/dist/storybook/assets/DotLoader.stories-B3OBu3X7.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/DotLoader.stories-B3OBu3X7'>;
}
declare module 'react-spinners/dist/storybook/assets/entry-preview-Bdjjc83v.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/entry-preview-Bdjjc83v'>;
}
declare module 'react-spinners/dist/storybook/assets/entry-preview-docs-Cnd6SSk3.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/entry-preview-docs-Cnd6SSk3'>;
}
declare module 'react-spinners/dist/storybook/assets/FadeLoader.stories-DjFNWHZS.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/FadeLoader.stories-DjFNWHZS'>;
}
declare module 'react-spinners/dist/storybook/assets/formatter-2WMMO6ZP-DXc4aD0z.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/formatter-2WMMO6ZP-DXc4aD0z'>;
}
declare module 'react-spinners/dist/storybook/assets/GridLoader.stories-DI6IVIyr.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/GridLoader.stories-DI6IVIyr'>;
}
declare module 'react-spinners/dist/storybook/assets/HashLoader.stories-DR38duvM.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/HashLoader.stories-DR38duvM'>;
}
declare module 'react-spinners/dist/storybook/assets/iframe-5p6UzXUn.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/iframe-5p6UzXUn'>;
}
declare module 'react-spinners/dist/storybook/assets/index-DrFu-skq.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/index-DrFu-skq'>;
}
declare module 'react-spinners/dist/storybook/assets/index-DXimoRZY.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/index-DXimoRZY'>;
}
declare module 'react-spinners/dist/storybook/assets/index-FeUjBnvO.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/index-FeUjBnvO'>;
}
declare module 'react-spinners/dist/storybook/assets/index-uubelm5h.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/index-uubelm5h'>;
}
declare module 'react-spinners/dist/storybook/assets/jsx-runtime-QvZ8i92b.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/jsx-runtime-QvZ8i92b'>;
}
declare module 'react-spinners/dist/storybook/assets/MoonLoader.stories-B55gekmJ.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/MoonLoader.stories-B55gekmJ'>;
}
declare module 'react-spinners/dist/storybook/assets/PacmanLoader.stories-DsX-8Wr7.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/PacmanLoader.stories-DsX-8Wr7'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-B4GcaC1c.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-B4GcaC1c'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-BAz7FMXc.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-BAz7FMXc'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-BmLvQvhz.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-BmLvQvhz'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-BpcF_O6y.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-BpcF_O6y'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-CJyji-Dt.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-CJyji-Dt'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-Ct5NkTJf.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-Ct5NkTJf'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-CwqMn10d.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-CwqMn10d'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-Db4Idchh.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-Db4Idchh'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-Df8P57N3.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-Df8P57N3'>;
}
declare module 'react-spinners/dist/storybook/assets/preview-TCN6m6T-.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/preview-TCN6m6T-'>;
}
declare module 'react-spinners/dist/storybook/assets/PropagateLoader.stories-Bz7zRdxH.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/PropagateLoader.stories-Bz7zRdxH'>;
}
declare module 'react-spinners/dist/storybook/assets/PuffLoader.stories-B763nhkv.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/PuffLoader.stories-B763nhkv'>;
}
declare module 'react-spinners/dist/storybook/assets/PulseLoader.stories-Q849BcQr.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/PulseLoader.stories-Q849BcQr'>;
}
declare module 'react-spinners/dist/storybook/assets/react-18-dxeXy74A.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/react-18-dxeXy74A'>;
}
declare module 'react-spinners/dist/storybook/assets/RingLoader.stories-BK7q4TmV.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/RingLoader.stories-BK7q4TmV'>;
}
declare module 'react-spinners/dist/storybook/assets/RiseLoader.stories-BkdUmN5k.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/RiseLoader.stories-BkdUmN5k'>;
}
declare module 'react-spinners/dist/storybook/assets/RotateLoader.stories-BL0wUnff.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/RotateLoader.stories-BL0wUnff'>;
}
declare module 'react-spinners/dist/storybook/assets/ScaleLoader.stories-E4q-HnXP.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/ScaleLoader.stories-E4q-HnXP'>;
}
declare module 'react-spinners/dist/storybook/assets/SkewLoader.stories-D7Yys5ID.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/SkewLoader.stories-D7Yys5ID'>;
}
declare module 'react-spinners/dist/storybook/assets/SquareLoader.stories-BB_nH-b2.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/SquareLoader.stories-BB_nH-b2'>;
}
declare module 'react-spinners/dist/storybook/assets/SyncLoader.stories-3_2T-rjZ.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/SyncLoader.stories-3_2T-rjZ'>;
}
declare module 'react-spinners/dist/storybook/assets/syntaxhighlighter-BP7B2CQK-D5V8MPXO.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/syntaxhighlighter-BP7B2CQK-D5V8MPXO'>;
}
declare module 'react-spinners/dist/storybook/assets/WithTooltip-KJL26V4Q-BoukyuhG.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/assets/WithTooltip-KJL26V4Q-BoukyuhG'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/essentials-actions-3/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/essentials-actions-3/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/essentials-backgrounds-4/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/essentials-backgrounds-4/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/essentials-controls-2/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/essentials-controls-2/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/essentials-measure-7/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/essentials-measure-7/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/essentials-outline-8/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/essentials-outline-8/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/essentials-toolbars-6/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/essentials-toolbars-6/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/essentials-viewport-5/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/essentials-viewport-5/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/interactions-9/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/interactions-9/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/links-1/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/links-1/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/storybook-13/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/storybook-13/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/storybook-canonical-link-12/register-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/storybook-canonical-link-12/register-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/storybook-core-server-presets-0/common-manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/storybook-core-server-presets-0/common-manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/storybook-dark-mode-esm-preset-10/manager-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/storybook-dark-mode-esm-preset-10/manager-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-addons/storybook-google-analytics-v4-11/register-bundle.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-addons/storybook-google-analytics-v4-11/register-bundle'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/chunk-B3YDJJJH.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/chunk-B3YDJJJH'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/chunk-BLWCBWKL.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/chunk-BLWCBWKL'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/chunk-GUVK2GTO.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/chunk-GUVK2GTO'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/chunk-LFRML3ZV.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/chunk-LFRML3ZV'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/chunk-MC7RAF2B.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/chunk-MC7RAF2B'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/chunk-ZR5JZWHI.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/chunk-ZR5JZWHI'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/formatter-2WMMO6ZP-JI7RHVTW.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/formatter-2WMMO6ZP-JI7RHVTW'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/globals-module-info.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/globals-module-info'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/globals-runtime.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/globals-runtime'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/globals.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/globals'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/index' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/index.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/runtime.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/runtime'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/syntaxhighlighter-BP7B2CQK-WOJYHKQR.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/syntaxhighlighter-BP7B2CQK-WOJYHKQR'>;
}
declare module 'react-spinners/dist/storybook/sb-manager/WithTooltip-KJL26V4Q-5LS5AN27.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-manager/WithTooltip-KJL26V4Q-5LS5AN27'>;
}
declare module 'react-spinners/dist/storybook/sb-preview/globals.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-preview/globals'>;
}
declare module 'react-spinners/dist/storybook/sb-preview/runtime.js' {
  declare module.exports: $Exports<'react-spinners/dist/storybook/sb-preview/runtime'>;
}
declare module 'react-spinners/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/DotLoader'>;
}
declare module 'react-spinners/esm/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/BarLoader'>;
}
declare module 'react-spinners/esm/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/BeatLoader'>;
}
declare module 'react-spinners/esm/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/BounceLoader'>;
}
declare module 'react-spinners/esm/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/CircleLoader'>;
}
declare module 'react-spinners/esm/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ClimbingBoxLoader'>;
}
declare module 'react-spinners/esm/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ClipLoader'>;
}
declare module 'react-spinners/esm/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ClockLoader'>;
}
declare module 'react-spinners/esm/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/DotLoader'>;
}
declare module 'react-spinners/esm/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/FadeLoader'>;
}
declare module 'react-spinners/esm/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/GridLoader'>;
}
declare module 'react-spinners/esm/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/HashLoader'>;
}
declare module 'react-spinners/esm/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/animation'>;
}
declare module 'react-spinners/esm/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/animation.server.test'>;
}
declare module 'react-spinners/esm/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/animation.test'>;
}
declare module 'react-spinners/esm/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/colors'>;
}
declare module 'react-spinners/esm/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/colors.test'>;
}
declare module 'react-spinners/esm/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/props'>;
}
declare module 'react-spinners/esm/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/unitConverter'>;
}
declare module 'react-spinners/esm/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/esm/helpers/unitConverter.test'>;
}
declare module 'react-spinners/esm/index' {
  declare module.exports: $Exports<'react-spinners/esm'>;
}
declare module 'react-spinners/esm/index.js' {
  declare module.exports: $Exports<'react-spinners/esm'>;
}
declare module 'react-spinners/esm/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/MoonLoader'>;
}
declare module 'react-spinners/esm/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PacmanLoader'>;
}
declare module 'react-spinners/esm/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PropagateLoader'>;
}
declare module 'react-spinners/esm/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PuffLoader'>;
}
declare module 'react-spinners/esm/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/PulseLoader'>;
}
declare module 'react-spinners/esm/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/RingLoader'>;
}
declare module 'react-spinners/esm/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/RiseLoader'>;
}
declare module 'react-spinners/esm/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/RotateLoader'>;
}
declare module 'react-spinners/esm/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/ScaleLoader'>;
}
declare module 'react-spinners/esm/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/SkewLoader'>;
}
declare module 'react-spinners/esm/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/SquareLoader'>;
}
declare module 'react-spinners/esm/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/esm/SyncLoader'>;
}
declare module 'react-spinners/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/FadeLoader'>;
}
declare module 'react-spinners/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/GridLoader'>;
}
declare module 'react-spinners/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/HashLoader'>;
}
declare module 'react-spinners/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/helpers/animation'>;
}
declare module 'react-spinners/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/animation.server.test'>;
}
declare module 'react-spinners/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/animation.test'>;
}
declare module 'react-spinners/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/helpers/colors'>;
}
declare module 'react-spinners/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/colors.test'>;
}
declare module 'react-spinners/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/helpers/props'>;
}
declare module 'react-spinners/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/helpers/unitConverter'>;
}
declare module 'react-spinners/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/helpers/unitConverter.test'>;
}
declare module 'react-spinners/index' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/index.js' {
  declare module.exports: $Exports<'react-spinners'>;
}
declare module 'react-spinners/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/MoonLoader'>;
}
declare module 'react-spinners/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/PacmanLoader'>;
}
declare module 'react-spinners/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/PropagateLoader'>;
}
declare module 'react-spinners/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/PuffLoader'>;
}
declare module 'react-spinners/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/PulseLoader'>;
}
declare module 'react-spinners/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/RingLoader'>;
}
declare module 'react-spinners/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/RiseLoader'>;
}
declare module 'react-spinners/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/RotateLoader'>;
}
declare module 'react-spinners/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/ScaleLoader'>;
}
declare module 'react-spinners/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/SkewLoader'>;
}
declare module 'react-spinners/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/SquareLoader'>;
}
declare module 'react-spinners/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/SyncLoader'>;
}
declare module 'react-spinners/umd/BarLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/BarLoader'>;
}
declare module 'react-spinners/umd/BeatLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/BeatLoader'>;
}
declare module 'react-spinners/umd/BounceLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/BounceLoader'>;
}
declare module 'react-spinners/umd/CircleLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/CircleLoader'>;
}
declare module 'react-spinners/umd/ClimbingBoxLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ClimbingBoxLoader'>;
}
declare module 'react-spinners/umd/ClipLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ClipLoader'>;
}
declare module 'react-spinners/umd/ClockLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ClockLoader'>;
}
declare module 'react-spinners/umd/DotLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/DotLoader'>;
}
declare module 'react-spinners/umd/FadeLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/FadeLoader'>;
}
declare module 'react-spinners/umd/GridLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/GridLoader'>;
}
declare module 'react-spinners/umd/HashLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/HashLoader'>;
}
declare module 'react-spinners/umd/helpers/animation.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/animation'>;
}
declare module 'react-spinners/umd/helpers/animation.server.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/animation.server.test'>;
}
declare module 'react-spinners/umd/helpers/animation.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/animation.test'>;
}
declare module 'react-spinners/umd/helpers/colors.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/colors'>;
}
declare module 'react-spinners/umd/helpers/colors.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/colors.test'>;
}
declare module 'react-spinners/umd/helpers/props.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/props'>;
}
declare module 'react-spinners/umd/helpers/unitConverter.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/unitConverter'>;
}
declare module 'react-spinners/umd/helpers/unitConverter.test.js' {
  declare module.exports: $Exports<'react-spinners/umd/helpers/unitConverter.test'>;
}
declare module 'react-spinners/umd/index' {
  declare module.exports: $Exports<'react-spinners/umd'>;
}
declare module 'react-spinners/umd/index.js' {
  declare module.exports: $Exports<'react-spinners/umd'>;
}
declare module 'react-spinners/umd/MoonLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/MoonLoader'>;
}
declare module 'react-spinners/umd/PacmanLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PacmanLoader'>;
}
declare module 'react-spinners/umd/PropagateLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PropagateLoader'>;
}
declare module 'react-spinners/umd/PuffLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PuffLoader'>;
}
declare module 'react-spinners/umd/PulseLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/PulseLoader'>;
}
declare module 'react-spinners/umd/RingLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/RingLoader'>;
}
declare module 'react-spinners/umd/RiseLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/RiseLoader'>;
}
declare module 'react-spinners/umd/RotateLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/RotateLoader'>;
}
declare module 'react-spinners/umd/ScaleLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/ScaleLoader'>;
}
declare module 'react-spinners/umd/SkewLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/SkewLoader'>;
}
declare module 'react-spinners/umd/SquareLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/SquareLoader'>;
}
declare module 'react-spinners/umd/SyncLoader.js' {
  declare module.exports: $Exports<'react-spinners/umd/SyncLoader'>;
}
