// flow-typed signature: 86d78f2097a4a31421c863292032dc03
// flow-typed version: <<STUB>>/react-meta-tags_v^1.0.1/flow_v0.165.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-meta-tags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-meta-tags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-meta-tags/dist/react-meta-tags.es' {
  declare module.exports: any;
}

declare module 'react-meta-tags/dist/react-meta-tags' {
  declare module.exports: any;
}

declare module 'react-meta-tags/dist/react-meta-tags.min' {
  declare module.exports: any;
}

declare module 'react-meta-tags/examples/app' {
  declare module.exports: any;
}

declare module 'react-meta-tags/examples/client' {
  declare module.exports: any;
}

declare module 'react-meta-tags/examples/shared' {
  declare module.exports: any;
}

declare module 'react-meta-tags/examples/shared/page1/page1' {
  declare module.exports: any;
}

declare module 'react-meta-tags/examples/shared/page2/page2' {
  declare module.exports: any;
}

declare module 'react-meta-tags/examples/shared/routes' {
  declare module.exports: any;
}

declare module 'react-meta-tags/lib' {
  declare module.exports: any;
}

declare module 'react-meta-tags/lib/meta_tags_context' {
  declare module.exports: any;
}

declare module 'react-meta-tags/lib/meta_tags_server' {
  declare module.exports: any;
}

declare module 'react-meta-tags/lib/meta_tags' {
  declare module.exports: any;
}

declare module 'react-meta-tags/lib/react_title' {
  declare module.exports: any;
}

declare module 'react-meta-tags/lib/utils' {
  declare module.exports: any;
}

declare module 'react-meta-tags/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-meta-tags/dist/react-meta-tags.es.js' {
  declare module.exports: $Exports<'react-meta-tags/dist/react-meta-tags.es'>;
}
declare module 'react-meta-tags/dist/react-meta-tags.js' {
  declare module.exports: $Exports<'react-meta-tags/dist/react-meta-tags'>;
}
declare module 'react-meta-tags/dist/react-meta-tags.min.js' {
  declare module.exports: $Exports<'react-meta-tags/dist/react-meta-tags.min'>;
}
declare module 'react-meta-tags/examples/app.js' {
  declare module.exports: $Exports<'react-meta-tags/examples/app'>;
}
declare module 'react-meta-tags/examples/client.js' {
  declare module.exports: $Exports<'react-meta-tags/examples/client'>;
}
declare module 'react-meta-tags/examples/shared/index' {
  declare module.exports: $Exports<'react-meta-tags/examples/shared'>;
}
declare module 'react-meta-tags/examples/shared/index.js' {
  declare module.exports: $Exports<'react-meta-tags/examples/shared'>;
}
declare module 'react-meta-tags/examples/shared/page1/page1.js' {
  declare module.exports: $Exports<'react-meta-tags/examples/shared/page1/page1'>;
}
declare module 'react-meta-tags/examples/shared/page2/page2.js' {
  declare module.exports: $Exports<'react-meta-tags/examples/shared/page2/page2'>;
}
declare module 'react-meta-tags/examples/shared/routes.js' {
  declare module.exports: $Exports<'react-meta-tags/examples/shared/routes'>;
}
declare module 'react-meta-tags/lib/index' {
  declare module.exports: $Exports<'react-meta-tags/lib'>;
}
declare module 'react-meta-tags/lib/index.js' {
  declare module.exports: $Exports<'react-meta-tags/lib'>;
}
declare module 'react-meta-tags/lib/meta_tags_context.js' {
  declare module.exports: $Exports<'react-meta-tags/lib/meta_tags_context'>;
}
declare module 'react-meta-tags/lib/meta_tags_server.js' {
  declare module.exports: $Exports<'react-meta-tags/lib/meta_tags_server'>;
}
declare module 'react-meta-tags/lib/meta_tags.js' {
  declare module.exports: $Exports<'react-meta-tags/lib/meta_tags'>;
}
declare module 'react-meta-tags/lib/react_title.js' {
  declare module.exports: $Exports<'react-meta-tags/lib/react_title'>;
}
declare module 'react-meta-tags/lib/utils.js' {
  declare module.exports: $Exports<'react-meta-tags/lib/utils'>;
}
declare module 'react-meta-tags/server.js' {
  declare module.exports: $Exports<'react-meta-tags/server'>;
}
