// flow-typed signature: 722a0877785bdfed6062bf335efc5947
// flow-typed version: <<STUB>>/serve_v^14.2.4/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serve' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serve/build/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serve/build/main.js' {
  declare module.exports: $Exports<'serve/build/main'>;
}
