// flow-typed signature: 0ca05bc6303848428f2730648ba8e271
// flow-typed version: <<STUB>>/type-to-reducer_v^1.2.0/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'type-to-reducer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'type-to-reducer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'type-to-reducer/lib' {
  declare module.exports: any;
}

declare module 'type-to-reducer/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'type-to-reducer/lib/index' {
  declare module.exports: $Exports<'type-to-reducer/lib'>;
}
declare module 'type-to-reducer/lib/index.js' {
  declare module.exports: $Exports<'type-to-reducer/lib'>;
}
declare module 'type-to-reducer/test/index.test.js' {
  declare module.exports: $Exports<'type-to-reducer/test/index.test'>;
}
