// flow-typed signature: 4442aba15d8445ed6d01990deeafe035
// flow-typed version: <<STUB>>/yup_v^1.5.0/flow_v0.256.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yup/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yup/index.esm.js' {
  declare module.exports: $Exports<'yup/index.esm'>;
}
declare module 'yup/index' {
  declare module.exports: $Exports<'yup'>;
}
declare module 'yup/index.js' {
  declare module.exports: $Exports<'yup'>;
}
