// flow-typed signature: 1b2ebea6b9c8513d7a560f4657b62212
// flow-typed version: <<STUB>>/@babel/eslint-parser_v^7.25.9/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/eslint-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/eslint-parser' {
  declare module.exports: any;
}
