// flow-typed signature: f0cf7d98efc315cb69e06ad1a70326bd
// flow-typed version: <<STUB>>/@babel/plugin-transform-modules-commonjs_v^7.26.3/flow_v0.257.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-modules-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-modules-commonjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-modules-commonjs/lib/dynamic-import' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-modules-commonjs/lib/hooks' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-modules-commonjs/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-transform-modules-commonjs/lib/lazy' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-modules-commonjs/lib/dynamic-import.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib/dynamic-import'>;
}
declare module '@babel/plugin-transform-modules-commonjs/lib/hooks.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib/hooks'>;
}
declare module '@babel/plugin-transform-modules-commonjs/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib'>;
}
declare module '@babel/plugin-transform-modules-commonjs/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib'>;
}
declare module '@babel/plugin-transform-modules-commonjs/lib/lazy.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-modules-commonjs/lib/lazy'>;
}
