// flow-typed signature: 2387cd5fee81e1efa42877c459f8b595
// flow-typed version: <<STUB>>/@rooks/use-did-mount_v^4.11.0/flow_v0.148.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rooks/use-did-mount'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rooks/use-did-mount' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rooks/use-did-mount/lib/index.esm' {
  declare module.exports: any;
}

declare module '@rooks/use-did-mount/lib' {
  declare module.exports: any;
}

declare module '@rooks/use-did-mount/lib/index.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rooks/use-did-mount/lib/index.esm.js' {
  declare module.exports: $Exports<'@rooks/use-did-mount/lib/index.esm'>;
}
declare module '@rooks/use-did-mount/lib/index' {
  declare module.exports: $Exports<'@rooks/use-did-mount/lib'>;
}
declare module '@rooks/use-did-mount/lib/index.js' {
  declare module.exports: $Exports<'@rooks/use-did-mount/lib'>;
}
declare module '@rooks/use-did-mount/lib/index.min.js' {
  declare module.exports: $Exports<'@rooks/use-did-mount/lib/index.min'>;
}
