// flow-typed signature: 70cd646f574ec0261cefb4765b90f810
// flow-typed version: <<STUB>>/@reduxjs/toolkit_v2.0.1/flow_v0.225.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reduxjs/toolkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reduxjs/toolkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reduxjs/toolkit/dist/cjs' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/query/cjs' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/query/react/cjs' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/query/react/rtk-query-react.legacy-esm' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/query/rtk-query.legacy-esm' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/react/cjs' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/react/redux-toolkit-react.legacy-esm' {
  declare module.exports: any;
}

declare module '@reduxjs/toolkit/dist/redux-toolkit.legacy-esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reduxjs/toolkit/dist/cjs/index' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/cjs'>;
}
declare module '@reduxjs/toolkit/dist/cjs/index.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/cjs'>;
}
declare module '@reduxjs/toolkit/dist/query/cjs/index' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/query/cjs'>;
}
declare module '@reduxjs/toolkit/dist/query/cjs/index.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/query/cjs'>;
}
declare module '@reduxjs/toolkit/dist/query/react/cjs/index' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/query/react/cjs'>;
}
declare module '@reduxjs/toolkit/dist/query/react/cjs/index.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/query/react/cjs'>;
}
declare module '@reduxjs/toolkit/dist/query/react/rtk-query-react.legacy-esm.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/query/react/rtk-query-react.legacy-esm'>;
}
declare module '@reduxjs/toolkit/dist/query/rtk-query.legacy-esm.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/query/rtk-query.legacy-esm'>;
}
declare module '@reduxjs/toolkit/dist/react/cjs/index' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/react/cjs'>;
}
declare module '@reduxjs/toolkit/dist/react/cjs/index.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/react/cjs'>;
}
declare module '@reduxjs/toolkit/dist/react/redux-toolkit-react.legacy-esm.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/react/redux-toolkit-react.legacy-esm'>;
}
declare module '@reduxjs/toolkit/dist/redux-toolkit.legacy-esm.js' {
  declare module.exports: $Exports<'@reduxjs/toolkit/dist/redux-toolkit.legacy-esm'>;
}
